import type { Metadata } from "next";
import { Anton, DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "@/components/Footer";

const anton = Anton({
  variable: "--font-anton",
  subsets: ["latin"],
  weight: "400",
});

const dmSans = DM_Sans({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${anton.variable} ${dmSans.variable} h-full antialiased`}
      data-theme="light"
    >
      <body
        className="min-h-full flex flex-col bg-white"
        cz-shortcut-listen="true"
      >
        <Navbar />
        <main className="flex-1 py-40 text-center">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
